import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {useLazyQuery, useMutation} from "@apollo/client";
import {GET_TEST_TOKEN_QUERY} from "@/graphql/query/getTestTokenQuery";
import {ME_QUERY} from "@/graphql/query/meQuery";
import React, {useState} from "react";
import {UPLOAD_PLAYER_DATE_MUTATION} from "@/graphql/mutation/uploadPlayerDate";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [getToken, {data, loading}] = useLazyQuery(GET_TEST_TOKEN_QUERY);
  const [getUser, {data:userData, loading:userLoading}] = useLazyQuery(ME_QUERY);

  const [uploadFile, {data:uploadData, loading:uploadLoading, error}] = useMutation(UPLOAD_PLAYER_DATE_MUTATION)


  const handleGetToken = async () => {
    const {data} = await getToken();
    localStorage.setItem('auth-token', data.getTestToken);
  }

  const handleGetUser = async () => {
    const {data}=await getUser();
    console.log(data,"data");
  }

  const [file, setFile] = useState<File | null>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      setFile(e.target.files[0]);
    }
  }

  const handleUpload = () => {
    const formData = new FormData();
    if(!file) return;
    formData.append('file', file);
    // image formData to blob
    // const blob = new Blob([file], {type: 'image/jpeg'});
    console.log(formData.get('file'), "formData.get('file')");
    uploadFile({variables: {auctionId: "641c8ad4cf00991e87eb31ba",multipartFile: formData.get('file')}})

  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={handleGetToken}>GET TOKEN</button>
        <button onClick={handleGetUser}>GET ME USER</button>
        upload file
        <input type="file" onChange={handleFileChange}/>
        <button onClick={handleUpload}>UPLOAD</button>


        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
